[build]
  command = "rm -rf node_modules/.cache && rm -rf dist && npm ci && npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"
  SECRETS_SCAN_ENABLED = "false"
  FORCE_REBUILD = "true"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
